package com.example.weappdemo.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class HotelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public HotelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHotelIdIsNull() {
            addCriterion("hotel_id is null");
            return (Criteria) this;
        }

        public Criteria andHotelIdIsNotNull() {
            addCriterion("hotel_id is not null");
            return (Criteria) this;
        }

        public Criteria andHotelIdEqualTo(String value) {
            addCriterion("hotel_id =", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotEqualTo(String value) {
            addCriterion("hotel_id <>", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdGreaterThan(String value) {
            addCriterion("hotel_id >", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdGreaterThanOrEqualTo(String value) {
            addCriterion("hotel_id >=", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLessThan(String value) {
            addCriterion("hotel_id <", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLessThanOrEqualTo(String value) {
            addCriterion("hotel_id <=", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLike(String value) {
            addCriterion("hotel_id like", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotLike(String value) {
            addCriterion("hotel_id not like", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdIn(List<String> values) {
            addCriterion("hotel_id in", values, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotIn(List<String> values) {
            addCriterion("hotel_id not in", values, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdBetween(String value1, String value2) {
            addCriterion("hotel_id between", value1, value2, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotBetween(String value1, String value2) {
            addCriterion("hotel_id not between", value1, value2, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelNameIsNull() {
            addCriterion("hotel_name is null");
            return (Criteria) this;
        }

        public Criteria andHotelNameIsNotNull() {
            addCriterion("hotel_name is not null");
            return (Criteria) this;
        }

        public Criteria andHotelNameEqualTo(String value) {
            addCriterion("hotel_name =", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotEqualTo(String value) {
            addCriterion("hotel_name <>", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameGreaterThan(String value) {
            addCriterion("hotel_name >", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameGreaterThanOrEqualTo(String value) {
            addCriterion("hotel_name >=", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLessThan(String value) {
            addCriterion("hotel_name <", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLessThanOrEqualTo(String value) {
            addCriterion("hotel_name <=", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLike(String value) {
            addCriterion("hotel_name like", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotLike(String value) {
            addCriterion("hotel_name not like", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameIn(List<String> values) {
            addCriterion("hotel_name in", values, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotIn(List<String> values) {
            addCriterion("hotel_name not in", values, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameBetween(String value1, String value2) {
            addCriterion("hotel_name between", value1, value2, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotBetween(String value1, String value2) {
            addCriterion("hotel_name not between", value1, value2, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelCityIsNull() {
            addCriterion("hotel_city is null");
            return (Criteria) this;
        }

        public Criteria andHotelCityIsNotNull() {
            addCriterion("hotel_city is not null");
            return (Criteria) this;
        }

        public Criteria andHotelCityEqualTo(String value) {
            addCriterion("hotel_city =", value, "hotelCity");
            return (Criteria) this;
        }

        public Criteria andHotelCityNotEqualTo(String value) {
            addCriterion("hotel_city <>", value, "hotelCity");
            return (Criteria) this;
        }

        public Criteria andHotelCityGreaterThan(String value) {
            addCriterion("hotel_city >", value, "hotelCity");
            return (Criteria) this;
        }

        public Criteria andHotelCityGreaterThanOrEqualTo(String value) {
            addCriterion("hotel_city >=", value, "hotelCity");
            return (Criteria) this;
        }

        public Criteria andHotelCityLessThan(String value) {
            addCriterion("hotel_city <", value, "hotelCity");
            return (Criteria) this;
        }

        public Criteria andHotelCityLessThanOrEqualTo(String value) {
            addCriterion("hotel_city <=", value, "hotelCity");
            return (Criteria) this;
        }

        public Criteria andHotelCityLike(String value) {
            addCriterion("hotel_city like", value, "hotelCity");
            return (Criteria) this;
        }

        public Criteria andHotelCityNotLike(String value) {
            addCriterion("hotel_city not like", value, "hotelCity");
            return (Criteria) this;
        }

        public Criteria andHotelCityIn(List<String> values) {
            addCriterion("hotel_city in", values, "hotelCity");
            return (Criteria) this;
        }

        public Criteria andHotelCityNotIn(List<String> values) {
            addCriterion("hotel_city not in", values, "hotelCity");
            return (Criteria) this;
        }

        public Criteria andHotelCityBetween(String value1, String value2) {
            addCriterion("hotel_city between", value1, value2, "hotelCity");
            return (Criteria) this;
        }

        public Criteria andHotelCityNotBetween(String value1, String value2) {
            addCriterion("hotel_city not between", value1, value2, "hotelCity");
            return (Criteria) this;
        }

        public Criteria andHotelDetailLocationIsNull() {
            addCriterion("hotel_detail_location is null");
            return (Criteria) this;
        }

        public Criteria andHotelDetailLocationIsNotNull() {
            addCriterion("hotel_detail_location is not null");
            return (Criteria) this;
        }

        public Criteria andHotelDetailLocationEqualTo(String value) {
            addCriterion("hotel_detail_location =", value, "hotelDetailLocation");
            return (Criteria) this;
        }

        public Criteria andHotelDetailLocationNotEqualTo(String value) {
            addCriterion("hotel_detail_location <>", value, "hotelDetailLocation");
            return (Criteria) this;
        }

        public Criteria andHotelDetailLocationGreaterThan(String value) {
            addCriterion("hotel_detail_location >", value, "hotelDetailLocation");
            return (Criteria) this;
        }

        public Criteria andHotelDetailLocationGreaterThanOrEqualTo(String value) {
            addCriterion("hotel_detail_location >=", value, "hotelDetailLocation");
            return (Criteria) this;
        }

        public Criteria andHotelDetailLocationLessThan(String value) {
            addCriterion("hotel_detail_location <", value, "hotelDetailLocation");
            return (Criteria) this;
        }

        public Criteria andHotelDetailLocationLessThanOrEqualTo(String value) {
            addCriterion("hotel_detail_location <=", value, "hotelDetailLocation");
            return (Criteria) this;
        }

        public Criteria andHotelDetailLocationLike(String value) {
            addCriterion("hotel_detail_location like", value, "hotelDetailLocation");
            return (Criteria) this;
        }

        public Criteria andHotelDetailLocationNotLike(String value) {
            addCriterion("hotel_detail_location not like", value, "hotelDetailLocation");
            return (Criteria) this;
        }

        public Criteria andHotelDetailLocationIn(List<String> values) {
            addCriterion("hotel_detail_location in", values, "hotelDetailLocation");
            return (Criteria) this;
        }

        public Criteria andHotelDetailLocationNotIn(List<String> values) {
            addCriterion("hotel_detail_location not in", values, "hotelDetailLocation");
            return (Criteria) this;
        }

        public Criteria andHotelDetailLocationBetween(String value1, String value2) {
            addCriterion("hotel_detail_location between", value1, value2, "hotelDetailLocation");
            return (Criteria) this;
        }

        public Criteria andHotelDetailLocationNotBetween(String value1, String value2) {
            addCriterion("hotel_detail_location not between", value1, value2, "hotelDetailLocation");
            return (Criteria) this;
        }

        public Criteria andHotelImgIsNull() {
            addCriterion("hotel_img is null");
            return (Criteria) this;
        }

        public Criteria andHotelImgIsNotNull() {
            addCriterion("hotel_img is not null");
            return (Criteria) this;
        }

        public Criteria andHotelImgEqualTo(String value) {
            addCriterion("hotel_img =", value, "hotelImg");
            return (Criteria) this;
        }

        public Criteria andHotelImgNotEqualTo(String value) {
            addCriterion("hotel_img <>", value, "hotelImg");
            return (Criteria) this;
        }

        public Criteria andHotelImgGreaterThan(String value) {
            addCriterion("hotel_img >", value, "hotelImg");
            return (Criteria) this;
        }

        public Criteria andHotelImgGreaterThanOrEqualTo(String value) {
            addCriterion("hotel_img >=", value, "hotelImg");
            return (Criteria) this;
        }

        public Criteria andHotelImgLessThan(String value) {
            addCriterion("hotel_img <", value, "hotelImg");
            return (Criteria) this;
        }

        public Criteria andHotelImgLessThanOrEqualTo(String value) {
            addCriterion("hotel_img <=", value, "hotelImg");
            return (Criteria) this;
        }

        public Criteria andHotelImgLike(String value) {
            addCriterion("hotel_img like", value, "hotelImg");
            return (Criteria) this;
        }

        public Criteria andHotelImgNotLike(String value) {
            addCriterion("hotel_img not like", value, "hotelImg");
            return (Criteria) this;
        }

        public Criteria andHotelImgIn(List<String> values) {
            addCriterion("hotel_img in", values, "hotelImg");
            return (Criteria) this;
        }

        public Criteria andHotelImgNotIn(List<String> values) {
            addCriterion("hotel_img not in", values, "hotelImg");
            return (Criteria) this;
        }

        public Criteria andHotelImgBetween(String value1, String value2) {
            addCriterion("hotel_img between", value1, value2, "hotelImg");
            return (Criteria) this;
        }

        public Criteria andHotelImgNotBetween(String value1, String value2) {
            addCriterion("hotel_img not between", value1, value2, "hotelImg");
            return (Criteria) this;
        }

        public Criteria andHotelLevelIsNull() {
            addCriterion("hotel_level is null");
            return (Criteria) this;
        }

        public Criteria andHotelLevelIsNotNull() {
            addCriterion("hotel_level is not null");
            return (Criteria) this;
        }

        public Criteria andHotelLevelEqualTo(Integer value) {
            addCriterion("hotel_level =", value, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelNotEqualTo(Integer value) {
            addCriterion("hotel_level <>", value, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelGreaterThan(Integer value) {
            addCriterion("hotel_level >", value, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("hotel_level >=", value, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelLessThan(Integer value) {
            addCriterion("hotel_level <", value, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelLessThanOrEqualTo(Integer value) {
            addCriterion("hotel_level <=", value, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelIn(List<Integer> values) {
            addCriterion("hotel_level in", values, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelNotIn(List<Integer> values) {
            addCriterion("hotel_level not in", values, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelBetween(Integer value1, Integer value2) {
            addCriterion("hotel_level between", value1, value2, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("hotel_level not between", value1, value2, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelTypeIsNull() {
            addCriterion("hotel_type is null");
            return (Criteria) this;
        }

        public Criteria andHotelTypeIsNotNull() {
            addCriterion("hotel_type is not null");
            return (Criteria) this;
        }

        public Criteria andHotelTypeEqualTo(String value) {
            addCriterion("hotel_type =", value, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeNotEqualTo(String value) {
            addCriterion("hotel_type <>", value, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeGreaterThan(String value) {
            addCriterion("hotel_type >", value, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeGreaterThanOrEqualTo(String value) {
            addCriterion("hotel_type >=", value, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeLessThan(String value) {
            addCriterion("hotel_type <", value, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeLessThanOrEqualTo(String value) {
            addCriterion("hotel_type <=", value, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeLike(String value) {
            addCriterion("hotel_type like", value, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeNotLike(String value) {
            addCriterion("hotel_type not like", value, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeIn(List<String> values) {
            addCriterion("hotel_type in", values, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeNotIn(List<String> values) {
            addCriterion("hotel_type not in", values, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeBetween(String value1, String value2) {
            addCriterion("hotel_type between", value1, value2, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeNotBetween(String value1, String value2) {
            addCriterion("hotel_type not between", value1, value2, "hotelType");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNumberIsNull() {
            addCriterion("basic_room_number is null");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNumberIsNotNull() {
            addCriterion("basic_room_number is not null");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNumberEqualTo(String value) {
            addCriterion("basic_room_number =", value, "basicRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNumberNotEqualTo(String value) {
            addCriterion("basic_room_number <>", value, "basicRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNumberGreaterThan(String value) {
            addCriterion("basic_room_number >", value, "basicRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNumberGreaterThanOrEqualTo(String value) {
            addCriterion("basic_room_number >=", value, "basicRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNumberLessThan(String value) {
            addCriterion("basic_room_number <", value, "basicRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNumberLessThanOrEqualTo(String value) {
            addCriterion("basic_room_number <=", value, "basicRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNumberLike(String value) {
            addCriterion("basic_room_number like", value, "basicRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNumberNotLike(String value) {
            addCriterion("basic_room_number not like", value, "basicRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNumberIn(List<String> values) {
            addCriterion("basic_room_number in", values, "basicRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNumberNotIn(List<String> values) {
            addCriterion("basic_room_number not in", values, "basicRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNumberBetween(String value1, String value2) {
            addCriterion("basic_room_number between", value1, value2, "basicRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNumberNotBetween(String value1, String value2) {
            addCriterion("basic_room_number not between", value1, value2, "basicRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBasicRoomPriceIsNull() {
            addCriterion("basic_room_price is null");
            return (Criteria) this;
        }

        public Criteria andBasicRoomPriceIsNotNull() {
            addCriterion("basic_room_price is not null");
            return (Criteria) this;
        }

        public Criteria andBasicRoomPriceEqualTo(String value) {
            addCriterion("basic_room_price =", value, "basicRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBasicRoomPriceNotEqualTo(String value) {
            addCriterion("basic_room_price <>", value, "basicRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBasicRoomPriceGreaterThan(String value) {
            addCriterion("basic_room_price >", value, "basicRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBasicRoomPriceGreaterThanOrEqualTo(String value) {
            addCriterion("basic_room_price >=", value, "basicRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBasicRoomPriceLessThan(String value) {
            addCriterion("basic_room_price <", value, "basicRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBasicRoomPriceLessThanOrEqualTo(String value) {
            addCriterion("basic_room_price <=", value, "basicRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBasicRoomPriceLike(String value) {
            addCriterion("basic_room_price like", value, "basicRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBasicRoomPriceNotLike(String value) {
            addCriterion("basic_room_price not like", value, "basicRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBasicRoomPriceIn(List<String> values) {
            addCriterion("basic_room_price in", values, "basicRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBasicRoomPriceNotIn(List<String> values) {
            addCriterion("basic_room_price not in", values, "basicRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBasicRoomPriceBetween(String value1, String value2) {
            addCriterion("basic_room_price between", value1, value2, "basicRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBasicRoomPriceNotBetween(String value1, String value2) {
            addCriterion("basic_room_price not between", value1, value2, "basicRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBasicRoomImgIsNull() {
            addCriterion("basic_room_img is null");
            return (Criteria) this;
        }

        public Criteria andBasicRoomImgIsNotNull() {
            addCriterion("basic_room_img is not null");
            return (Criteria) this;
        }

        public Criteria andBasicRoomImgEqualTo(String value) {
            addCriterion("basic_room_img =", value, "basicRoomImg");
            return (Criteria) this;
        }

        public Criteria andBasicRoomImgNotEqualTo(String value) {
            addCriterion("basic_room_img <>", value, "basicRoomImg");
            return (Criteria) this;
        }

        public Criteria andBasicRoomImgGreaterThan(String value) {
            addCriterion("basic_room_img >", value, "basicRoomImg");
            return (Criteria) this;
        }

        public Criteria andBasicRoomImgGreaterThanOrEqualTo(String value) {
            addCriterion("basic_room_img >=", value, "basicRoomImg");
            return (Criteria) this;
        }

        public Criteria andBasicRoomImgLessThan(String value) {
            addCriterion("basic_room_img <", value, "basicRoomImg");
            return (Criteria) this;
        }

        public Criteria andBasicRoomImgLessThanOrEqualTo(String value) {
            addCriterion("basic_room_img <=", value, "basicRoomImg");
            return (Criteria) this;
        }

        public Criteria andBasicRoomImgLike(String value) {
            addCriterion("basic_room_img like", value, "basicRoomImg");
            return (Criteria) this;
        }

        public Criteria andBasicRoomImgNotLike(String value) {
            addCriterion("basic_room_img not like", value, "basicRoomImg");
            return (Criteria) this;
        }

        public Criteria andBasicRoomImgIn(List<String> values) {
            addCriterion("basic_room_img in", values, "basicRoomImg");
            return (Criteria) this;
        }

        public Criteria andBasicRoomImgNotIn(List<String> values) {
            addCriterion("basic_room_img not in", values, "basicRoomImg");
            return (Criteria) this;
        }

        public Criteria andBasicRoomImgBetween(String value1, String value2) {
            addCriterion("basic_room_img between", value1, value2, "basicRoomImg");
            return (Criteria) this;
        }

        public Criteria andBasicRoomImgNotBetween(String value1, String value2) {
            addCriterion("basic_room_img not between", value1, value2, "basicRoomImg");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNotesIsNull() {
            addCriterion("basic_room_notes is null");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNotesIsNotNull() {
            addCriterion("basic_room_notes is not null");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNotesEqualTo(String value) {
            addCriterion("basic_room_notes =", value, "basicRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNotesNotEqualTo(String value) {
            addCriterion("basic_room_notes <>", value, "basicRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNotesGreaterThan(String value) {
            addCriterion("basic_room_notes >", value, "basicRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNotesGreaterThanOrEqualTo(String value) {
            addCriterion("basic_room_notes >=", value, "basicRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNotesLessThan(String value) {
            addCriterion("basic_room_notes <", value, "basicRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNotesLessThanOrEqualTo(String value) {
            addCriterion("basic_room_notes <=", value, "basicRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNotesLike(String value) {
            addCriterion("basic_room_notes like", value, "basicRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNotesNotLike(String value) {
            addCriterion("basic_room_notes not like", value, "basicRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNotesIn(List<String> values) {
            addCriterion("basic_room_notes in", values, "basicRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNotesNotIn(List<String> values) {
            addCriterion("basic_room_notes not in", values, "basicRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNotesBetween(String value1, String value2) {
            addCriterion("basic_room_notes between", value1, value2, "basicRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBasicRoomNotesNotBetween(String value1, String value2) {
            addCriterion("basic_room_notes not between", value1, value2, "basicRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBigRoomNumberIsNull() {
            addCriterion("big_room_number is null");
            return (Criteria) this;
        }

        public Criteria andBigRoomNumberIsNotNull() {
            addCriterion("big_room_number is not null");
            return (Criteria) this;
        }

        public Criteria andBigRoomNumberEqualTo(String value) {
            addCriterion("big_room_number =", value, "bigRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBigRoomNumberNotEqualTo(String value) {
            addCriterion("big_room_number <>", value, "bigRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBigRoomNumberGreaterThan(String value) {
            addCriterion("big_room_number >", value, "bigRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBigRoomNumberGreaterThanOrEqualTo(String value) {
            addCriterion("big_room_number >=", value, "bigRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBigRoomNumberLessThan(String value) {
            addCriterion("big_room_number <", value, "bigRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBigRoomNumberLessThanOrEqualTo(String value) {
            addCriterion("big_room_number <=", value, "bigRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBigRoomNumberLike(String value) {
            addCriterion("big_room_number like", value, "bigRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBigRoomNumberNotLike(String value) {
            addCriterion("big_room_number not like", value, "bigRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBigRoomNumberIn(List<String> values) {
            addCriterion("big_room_number in", values, "bigRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBigRoomNumberNotIn(List<String> values) {
            addCriterion("big_room_number not in", values, "bigRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBigRoomNumberBetween(String value1, String value2) {
            addCriterion("big_room_number between", value1, value2, "bigRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBigRoomNumberNotBetween(String value1, String value2) {
            addCriterion("big_room_number not between", value1, value2, "bigRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBigRoomPriceIsNull() {
            addCriterion("big_room_price is null");
            return (Criteria) this;
        }

        public Criteria andBigRoomPriceIsNotNull() {
            addCriterion("big_room_price is not null");
            return (Criteria) this;
        }

        public Criteria andBigRoomPriceEqualTo(String value) {
            addCriterion("big_room_price =", value, "bigRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBigRoomPriceNotEqualTo(String value) {
            addCriterion("big_room_price <>", value, "bigRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBigRoomPriceGreaterThan(String value) {
            addCriterion("big_room_price >", value, "bigRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBigRoomPriceGreaterThanOrEqualTo(String value) {
            addCriterion("big_room_price >=", value, "bigRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBigRoomPriceLessThan(String value) {
            addCriterion("big_room_price <", value, "bigRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBigRoomPriceLessThanOrEqualTo(String value) {
            addCriterion("big_room_price <=", value, "bigRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBigRoomPriceLike(String value) {
            addCriterion("big_room_price like", value, "bigRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBigRoomPriceNotLike(String value) {
            addCriterion("big_room_price not like", value, "bigRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBigRoomPriceIn(List<String> values) {
            addCriterion("big_room_price in", values, "bigRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBigRoomPriceNotIn(List<String> values) {
            addCriterion("big_room_price not in", values, "bigRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBigRoomPriceBetween(String value1, String value2) {
            addCriterion("big_room_price between", value1, value2, "bigRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBigRoomPriceNotBetween(String value1, String value2) {
            addCriterion("big_room_price not between", value1, value2, "bigRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBigRoomNotesIsNull() {
            addCriterion("big_room_notes is null");
            return (Criteria) this;
        }

        public Criteria andBigRoomNotesIsNotNull() {
            addCriterion("big_room_notes is not null");
            return (Criteria) this;
        }

        public Criteria andBigRoomNotesEqualTo(String value) {
            addCriterion("big_room_notes =", value, "bigRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBigRoomNotesNotEqualTo(String value) {
            addCriterion("big_room_notes <>", value, "bigRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBigRoomNotesGreaterThan(String value) {
            addCriterion("big_room_notes >", value, "bigRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBigRoomNotesGreaterThanOrEqualTo(String value) {
            addCriterion("big_room_notes >=", value, "bigRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBigRoomNotesLessThan(String value) {
            addCriterion("big_room_notes <", value, "bigRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBigRoomNotesLessThanOrEqualTo(String value) {
            addCriterion("big_room_notes <=", value, "bigRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBigRoomNotesLike(String value) {
            addCriterion("big_room_notes like", value, "bigRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBigRoomNotesNotLike(String value) {
            addCriterion("big_room_notes not like", value, "bigRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBigRoomNotesIn(List<String> values) {
            addCriterion("big_room_notes in", values, "bigRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBigRoomNotesNotIn(List<String> values) {
            addCriterion("big_room_notes not in", values, "bigRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBigRoomNotesBetween(String value1, String value2) {
            addCriterion("big_room_notes between", value1, value2, "bigRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBigRoomNotesNotBetween(String value1, String value2) {
            addCriterion("big_room_notes not between", value1, value2, "bigRoomNotes");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNumberIsNull() {
            addCriterion("double_room_number is null");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNumberIsNotNull() {
            addCriterion("double_room_number is not null");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNumberEqualTo(String value) {
            addCriterion("double_room_number =", value, "doubleRoomNumber");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNumberNotEqualTo(String value) {
            addCriterion("double_room_number <>", value, "doubleRoomNumber");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNumberGreaterThan(String value) {
            addCriterion("double_room_number >", value, "doubleRoomNumber");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNumberGreaterThanOrEqualTo(String value) {
            addCriterion("double_room_number >=", value, "doubleRoomNumber");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNumberLessThan(String value) {
            addCriterion("double_room_number <", value, "doubleRoomNumber");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNumberLessThanOrEqualTo(String value) {
            addCriterion("double_room_number <=", value, "doubleRoomNumber");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNumberLike(String value) {
            addCriterion("double_room_number like", value, "doubleRoomNumber");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNumberNotLike(String value) {
            addCriterion("double_room_number not like", value, "doubleRoomNumber");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNumberIn(List<String> values) {
            addCriterion("double_room_number in", values, "doubleRoomNumber");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNumberNotIn(List<String> values) {
            addCriterion("double_room_number not in", values, "doubleRoomNumber");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNumberBetween(String value1, String value2) {
            addCriterion("double_room_number between", value1, value2, "doubleRoomNumber");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNumberNotBetween(String value1, String value2) {
            addCriterion("double_room_number not between", value1, value2, "doubleRoomNumber");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomPriceIsNull() {
            addCriterion("double_room_price is null");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomPriceIsNotNull() {
            addCriterion("double_room_price is not null");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomPriceEqualTo(String value) {
            addCriterion("double_room_price =", value, "doubleRoomPrice");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomPriceNotEqualTo(String value) {
            addCriterion("double_room_price <>", value, "doubleRoomPrice");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomPriceGreaterThan(String value) {
            addCriterion("double_room_price >", value, "doubleRoomPrice");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomPriceGreaterThanOrEqualTo(String value) {
            addCriterion("double_room_price >=", value, "doubleRoomPrice");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomPriceLessThan(String value) {
            addCriterion("double_room_price <", value, "doubleRoomPrice");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomPriceLessThanOrEqualTo(String value) {
            addCriterion("double_room_price <=", value, "doubleRoomPrice");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomPriceLike(String value) {
            addCriterion("double_room_price like", value, "doubleRoomPrice");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomPriceNotLike(String value) {
            addCriterion("double_room_price not like", value, "doubleRoomPrice");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomPriceIn(List<String> values) {
            addCriterion("double_room_price in", values, "doubleRoomPrice");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomPriceNotIn(List<String> values) {
            addCriterion("double_room_price not in", values, "doubleRoomPrice");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomPriceBetween(String value1, String value2) {
            addCriterion("double_room_price between", value1, value2, "doubleRoomPrice");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomPriceNotBetween(String value1, String value2) {
            addCriterion("double_room_price not between", value1, value2, "doubleRoomPrice");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNotesIsNull() {
            addCriterion("double_room_notes is null");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNotesIsNotNull() {
            addCriterion("double_room_notes is not null");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNotesEqualTo(String value) {
            addCriterion("double_room_notes =", value, "doubleRoomNotes");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNotesNotEqualTo(String value) {
            addCriterion("double_room_notes <>", value, "doubleRoomNotes");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNotesGreaterThan(String value) {
            addCriterion("double_room_notes >", value, "doubleRoomNotes");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNotesGreaterThanOrEqualTo(String value) {
            addCriterion("double_room_notes >=", value, "doubleRoomNotes");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNotesLessThan(String value) {
            addCriterion("double_room_notes <", value, "doubleRoomNotes");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNotesLessThanOrEqualTo(String value) {
            addCriterion("double_room_notes <=", value, "doubleRoomNotes");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNotesLike(String value) {
            addCriterion("double_room_notes like", value, "doubleRoomNotes");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNotesNotLike(String value) {
            addCriterion("double_room_notes not like", value, "doubleRoomNotes");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNotesIn(List<String> values) {
            addCriterion("double_room_notes in", values, "doubleRoomNotes");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNotesNotIn(List<String> values) {
            addCriterion("double_room_notes not in", values, "doubleRoomNotes");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNotesBetween(String value1, String value2) {
            addCriterion("double_room_notes between", value1, value2, "doubleRoomNotes");
            return (Criteria) this;
        }

        public Criteria andDoubleRoomNotesNotBetween(String value1, String value2) {
            addCriterion("double_room_notes not between", value1, value2, "doubleRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBestRoomNumberIsNull() {
            addCriterion("best_room_number is null");
            return (Criteria) this;
        }

        public Criteria andBestRoomNumberIsNotNull() {
            addCriterion("best_room_number is not null");
            return (Criteria) this;
        }

        public Criteria andBestRoomNumberEqualTo(String value) {
            addCriterion("best_room_number =", value, "bestRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBestRoomNumberNotEqualTo(String value) {
            addCriterion("best_room_number <>", value, "bestRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBestRoomNumberGreaterThan(String value) {
            addCriterion("best_room_number >", value, "bestRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBestRoomNumberGreaterThanOrEqualTo(String value) {
            addCriterion("best_room_number >=", value, "bestRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBestRoomNumberLessThan(String value) {
            addCriterion("best_room_number <", value, "bestRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBestRoomNumberLessThanOrEqualTo(String value) {
            addCriterion("best_room_number <=", value, "bestRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBestRoomNumberLike(String value) {
            addCriterion("best_room_number like", value, "bestRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBestRoomNumberNotLike(String value) {
            addCriterion("best_room_number not like", value, "bestRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBestRoomNumberIn(List<String> values) {
            addCriterion("best_room_number in", values, "bestRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBestRoomNumberNotIn(List<String> values) {
            addCriterion("best_room_number not in", values, "bestRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBestRoomNumberBetween(String value1, String value2) {
            addCriterion("best_room_number between", value1, value2, "bestRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBestRoomNumberNotBetween(String value1, String value2) {
            addCriterion("best_room_number not between", value1, value2, "bestRoomNumber");
            return (Criteria) this;
        }

        public Criteria andBestRoomPriceIsNull() {
            addCriterion("best_room_price is null");
            return (Criteria) this;
        }

        public Criteria andBestRoomPriceIsNotNull() {
            addCriterion("best_room_price is not null");
            return (Criteria) this;
        }

        public Criteria andBestRoomPriceEqualTo(String value) {
            addCriterion("best_room_price =", value, "bestRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBestRoomPriceNotEqualTo(String value) {
            addCriterion("best_room_price <>", value, "bestRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBestRoomPriceGreaterThan(String value) {
            addCriterion("best_room_price >", value, "bestRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBestRoomPriceGreaterThanOrEqualTo(String value) {
            addCriterion("best_room_price >=", value, "bestRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBestRoomPriceLessThan(String value) {
            addCriterion("best_room_price <", value, "bestRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBestRoomPriceLessThanOrEqualTo(String value) {
            addCriterion("best_room_price <=", value, "bestRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBestRoomPriceLike(String value) {
            addCriterion("best_room_price like", value, "bestRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBestRoomPriceNotLike(String value) {
            addCriterion("best_room_price not like", value, "bestRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBestRoomPriceIn(List<String> values) {
            addCriterion("best_room_price in", values, "bestRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBestRoomPriceNotIn(List<String> values) {
            addCriterion("best_room_price not in", values, "bestRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBestRoomPriceBetween(String value1, String value2) {
            addCriterion("best_room_price between", value1, value2, "bestRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBestRoomPriceNotBetween(String value1, String value2) {
            addCriterion("best_room_price not between", value1, value2, "bestRoomPrice");
            return (Criteria) this;
        }

        public Criteria andBestRoomNotesIsNull() {
            addCriterion("best_room_notes is null");
            return (Criteria) this;
        }

        public Criteria andBestRoomNotesIsNotNull() {
            addCriterion("best_room_notes is not null");
            return (Criteria) this;
        }

        public Criteria andBestRoomNotesEqualTo(String value) {
            addCriterion("best_room_notes =", value, "bestRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBestRoomNotesNotEqualTo(String value) {
            addCriterion("best_room_notes <>", value, "bestRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBestRoomNotesGreaterThan(String value) {
            addCriterion("best_room_notes >", value, "bestRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBestRoomNotesGreaterThanOrEqualTo(String value) {
            addCriterion("best_room_notes >=", value, "bestRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBestRoomNotesLessThan(String value) {
            addCriterion("best_room_notes <", value, "bestRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBestRoomNotesLessThanOrEqualTo(String value) {
            addCriterion("best_room_notes <=", value, "bestRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBestRoomNotesLike(String value) {
            addCriterion("best_room_notes like", value, "bestRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBestRoomNotesNotLike(String value) {
            addCriterion("best_room_notes not like", value, "bestRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBestRoomNotesIn(List<String> values) {
            addCriterion("best_room_notes in", values, "bestRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBestRoomNotesNotIn(List<String> values) {
            addCriterion("best_room_notes not in", values, "bestRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBestRoomNotesBetween(String value1, String value2) {
            addCriterion("best_room_notes between", value1, value2, "bestRoomNotes");
            return (Criteria) this;
        }

        public Criteria andBestRoomNotesNotBetween(String value1, String value2) {
            addCriterion("best_room_notes not between", value1, value2, "bestRoomNotes");
            return (Criteria) this;
        }

        public Criteria andHotelScoreIsNull() {
            addCriterion("hotel_score is null");
            return (Criteria) this;
        }

        public Criteria andHotelScoreIsNotNull() {
            addCriterion("hotel_score is not null");
            return (Criteria) this;
        }

        public Criteria andHotelScoreEqualTo(BigDecimal value) {
            addCriterion("hotel_score =", value, "hotelScore");
            return (Criteria) this;
        }

        public Criteria andHotelScoreNotEqualTo(BigDecimal value) {
            addCriterion("hotel_score <>", value, "hotelScore");
            return (Criteria) this;
        }

        public Criteria andHotelScoreGreaterThan(BigDecimal value) {
            addCriterion("hotel_score >", value, "hotelScore");
            return (Criteria) this;
        }

        public Criteria andHotelScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("hotel_score >=", value, "hotelScore");
            return (Criteria) this;
        }

        public Criteria andHotelScoreLessThan(BigDecimal value) {
            addCriterion("hotel_score <", value, "hotelScore");
            return (Criteria) this;
        }

        public Criteria andHotelScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("hotel_score <=", value, "hotelScore");
            return (Criteria) this;
        }

        public Criteria andHotelScoreIn(List<BigDecimal> values) {
            addCriterion("hotel_score in", values, "hotelScore");
            return (Criteria) this;
        }

        public Criteria andHotelScoreNotIn(List<BigDecimal> values) {
            addCriterion("hotel_score not in", values, "hotelScore");
            return (Criteria) this;
        }

        public Criteria andHotelScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hotel_score between", value1, value2, "hotelScore");
            return (Criteria) this;
        }

        public Criteria andHotelScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hotel_score not between", value1, value2, "hotelScore");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel_list
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 04 10:51:59 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}