package com.example.weappdemo.bean;

import java.io.Serializable;
import java.math.BigDecimal;

public class Hotel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.hotel_id
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.hotel_name
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String hotelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.hotel_city
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String hotelCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.hotel_detail_location
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String hotelDetailLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.hotel_img
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String hotelImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.hotel_level
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private Integer hotelLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.hotel_type
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String hotelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.basic_room_number
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String basicRoomNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.basic_room_price
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String basicRoomPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.basic_room_img
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String basicRoomImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.basic_room_notes
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String basicRoomNotes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.big_room_number
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String bigRoomNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.big_room_price
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String bigRoomPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.big_room_notes
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String bigRoomNotes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.double_room_number
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String doubleRoomNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.double_room_price
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String doubleRoomPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.double_room_notes
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String doubleRoomNotes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.best_room_number
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String bestRoomNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.best_room_price
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String bestRoomPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.best_room_notes
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String bestRoomNotes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_list.hotel_score
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private BigDecimal hotelScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.hotel_id
     *
     * @return the value of hotel_list.hotel_id
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withHotelId(String hotelId) {
        this.setHotelId(hotelId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.hotel_id
     *
     * @param hotelId the value for hotel_list.hotel_id
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setHotelId(String hotelId) {
        this.hotelId = hotelId == null ? null : hotelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.hotel_name
     *
     * @return the value of hotel_list.hotel_name
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withHotelName(String hotelName) {
        this.setHotelName(hotelName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.hotel_name
     *
     * @param hotelName the value for hotel_list.hotel_name
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName == null ? null : hotelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.hotel_city
     *
     * @return the value of hotel_list.hotel_city
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getHotelCity() {
        return hotelCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withHotelCity(String hotelCity) {
        this.setHotelCity(hotelCity);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.hotel_city
     *
     * @param hotelCity the value for hotel_list.hotel_city
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setHotelCity(String hotelCity) {
        this.hotelCity = hotelCity == null ? null : hotelCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.hotel_detail_location
     *
     * @return the value of hotel_list.hotel_detail_location
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getHotelDetailLocation() {
        return hotelDetailLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withHotelDetailLocation(String hotelDetailLocation) {
        this.setHotelDetailLocation(hotelDetailLocation);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.hotel_detail_location
     *
     * @param hotelDetailLocation the value for hotel_list.hotel_detail_location
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setHotelDetailLocation(String hotelDetailLocation) {
        this.hotelDetailLocation = hotelDetailLocation == null ? null : hotelDetailLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.hotel_img
     *
     * @return the value of hotel_list.hotel_img
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getHotelImg() {
        return hotelImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withHotelImg(String hotelImg) {
        this.setHotelImg(hotelImg);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.hotel_img
     *
     * @param hotelImg the value for hotel_list.hotel_img
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setHotelImg(String hotelImg) {
        this.hotelImg = hotelImg == null ? null : hotelImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.hotel_level
     *
     * @return the value of hotel_list.hotel_level
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Integer getHotelLevel() {
        return hotelLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withHotelLevel(Integer hotelLevel) {
        this.setHotelLevel(hotelLevel);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.hotel_level
     *
     * @param hotelLevel the value for hotel_list.hotel_level
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setHotelLevel(Integer hotelLevel) {
        this.hotelLevel = hotelLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.hotel_type
     *
     * @return the value of hotel_list.hotel_type
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getHotelType() {
        return hotelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withHotelType(String hotelType) {
        this.setHotelType(hotelType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.hotel_type
     *
     * @param hotelType the value for hotel_list.hotel_type
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setHotelType(String hotelType) {
        this.hotelType = hotelType == null ? null : hotelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.basic_room_number
     *
     * @return the value of hotel_list.basic_room_number
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getBasicRoomNumber() {
        return basicRoomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withBasicRoomNumber(String basicRoomNumber) {
        this.setBasicRoomNumber(basicRoomNumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.basic_room_number
     *
     * @param basicRoomNumber the value for hotel_list.basic_room_number
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setBasicRoomNumber(String basicRoomNumber) {
        this.basicRoomNumber = basicRoomNumber == null ? null : basicRoomNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.basic_room_price
     *
     * @return the value of hotel_list.basic_room_price
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getBasicRoomPrice() {
        return basicRoomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withBasicRoomPrice(String basicRoomPrice) {
        this.setBasicRoomPrice(basicRoomPrice);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.basic_room_price
     *
     * @param basicRoomPrice the value for hotel_list.basic_room_price
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setBasicRoomPrice(String basicRoomPrice) {
        this.basicRoomPrice = basicRoomPrice == null ? null : basicRoomPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.basic_room_img
     *
     * @return the value of hotel_list.basic_room_img
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getBasicRoomImg() {
        return basicRoomImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withBasicRoomImg(String basicRoomImg) {
        this.setBasicRoomImg(basicRoomImg);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.basic_room_img
     *
     * @param basicRoomImg the value for hotel_list.basic_room_img
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setBasicRoomImg(String basicRoomImg) {
        this.basicRoomImg = basicRoomImg == null ? null : basicRoomImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.basic_room_notes
     *
     * @return the value of hotel_list.basic_room_notes
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getBasicRoomNotes() {
        return basicRoomNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withBasicRoomNotes(String basicRoomNotes) {
        this.setBasicRoomNotes(basicRoomNotes);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.basic_room_notes
     *
     * @param basicRoomNotes the value for hotel_list.basic_room_notes
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setBasicRoomNotes(String basicRoomNotes) {
        this.basicRoomNotes = basicRoomNotes == null ? null : basicRoomNotes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.big_room_number
     *
     * @return the value of hotel_list.big_room_number
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getBigRoomNumber() {
        return bigRoomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withBigRoomNumber(String bigRoomNumber) {
        this.setBigRoomNumber(bigRoomNumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.big_room_number
     *
     * @param bigRoomNumber the value for hotel_list.big_room_number
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setBigRoomNumber(String bigRoomNumber) {
        this.bigRoomNumber = bigRoomNumber == null ? null : bigRoomNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.big_room_price
     *
     * @return the value of hotel_list.big_room_price
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getBigRoomPrice() {
        return bigRoomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withBigRoomPrice(String bigRoomPrice) {
        this.setBigRoomPrice(bigRoomPrice);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.big_room_price
     *
     * @param bigRoomPrice the value for hotel_list.big_room_price
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setBigRoomPrice(String bigRoomPrice) {
        this.bigRoomPrice = bigRoomPrice == null ? null : bigRoomPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.big_room_notes
     *
     * @return the value of hotel_list.big_room_notes
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getBigRoomNotes() {
        return bigRoomNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withBigRoomNotes(String bigRoomNotes) {
        this.setBigRoomNotes(bigRoomNotes);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.big_room_notes
     *
     * @param bigRoomNotes the value for hotel_list.big_room_notes
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setBigRoomNotes(String bigRoomNotes) {
        this.bigRoomNotes = bigRoomNotes == null ? null : bigRoomNotes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.double_room_number
     *
     * @return the value of hotel_list.double_room_number
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getDoubleRoomNumber() {
        return doubleRoomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withDoubleRoomNumber(String doubleRoomNumber) {
        this.setDoubleRoomNumber(doubleRoomNumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.double_room_number
     *
     * @param doubleRoomNumber the value for hotel_list.double_room_number
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setDoubleRoomNumber(String doubleRoomNumber) {
        this.doubleRoomNumber = doubleRoomNumber == null ? null : doubleRoomNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.double_room_price
     *
     * @return the value of hotel_list.double_room_price
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getDoubleRoomPrice() {
        return doubleRoomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withDoubleRoomPrice(String doubleRoomPrice) {
        this.setDoubleRoomPrice(doubleRoomPrice);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.double_room_price
     *
     * @param doubleRoomPrice the value for hotel_list.double_room_price
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setDoubleRoomPrice(String doubleRoomPrice) {
        this.doubleRoomPrice = doubleRoomPrice == null ? null : doubleRoomPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.double_room_notes
     *
     * @return the value of hotel_list.double_room_notes
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getDoubleRoomNotes() {
        return doubleRoomNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withDoubleRoomNotes(String doubleRoomNotes) {
        this.setDoubleRoomNotes(doubleRoomNotes);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.double_room_notes
     *
     * @param doubleRoomNotes the value for hotel_list.double_room_notes
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setDoubleRoomNotes(String doubleRoomNotes) {
        this.doubleRoomNotes = doubleRoomNotes == null ? null : doubleRoomNotes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.best_room_number
     *
     * @return the value of hotel_list.best_room_number
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getBestRoomNumber() {
        return bestRoomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withBestRoomNumber(String bestRoomNumber) {
        this.setBestRoomNumber(bestRoomNumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.best_room_number
     *
     * @param bestRoomNumber the value for hotel_list.best_room_number
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setBestRoomNumber(String bestRoomNumber) {
        this.bestRoomNumber = bestRoomNumber == null ? null : bestRoomNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.best_room_price
     *
     * @return the value of hotel_list.best_room_price
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getBestRoomPrice() {
        return bestRoomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withBestRoomPrice(String bestRoomPrice) {
        this.setBestRoomPrice(bestRoomPrice);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.best_room_price
     *
     * @param bestRoomPrice the value for hotel_list.best_room_price
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setBestRoomPrice(String bestRoomPrice) {
        this.bestRoomPrice = bestRoomPrice == null ? null : bestRoomPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.best_room_notes
     *
     * @return the value of hotel_list.best_room_notes
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getBestRoomNotes() {
        return bestRoomNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withBestRoomNotes(String bestRoomNotes) {
        this.setBestRoomNotes(bestRoomNotes);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.best_room_notes
     *
     * @param bestRoomNotes the value for hotel_list.best_room_notes
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setBestRoomNotes(String bestRoomNotes) {
        this.bestRoomNotes = bestRoomNotes == null ? null : bestRoomNotes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_list.hotel_score
     *
     * @return the value of hotel_list.hotel_score
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public BigDecimal getHotelScore() {
        return hotelScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Hotel withHotelScore(BigDecimal hotelScore) {
        this.setHotelScore(hotelScore);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_list.hotel_score
     *
     * @param hotelScore the value for hotel_list.hotel_score
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setHotelScore(BigDecimal hotelScore) {
        this.hotelScore = hotelScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hotelId=").append(hotelId);
        sb.append(", hotelName=").append(hotelName);
        sb.append(", hotelCity=").append(hotelCity);
        sb.append(", hotelDetailLocation=").append(hotelDetailLocation);
        sb.append(", hotelImg=").append(hotelImg);
        sb.append(", hotelLevel=").append(hotelLevel);
        sb.append(", hotelType=").append(hotelType);
        sb.append(", basicRoomNumber=").append(basicRoomNumber);
        sb.append(", basicRoomPrice=").append(basicRoomPrice);
        sb.append(", basicRoomImg=").append(basicRoomImg);
        sb.append(", basicRoomNotes=").append(basicRoomNotes);
        sb.append(", bigRoomNumber=").append(bigRoomNumber);
        sb.append(", bigRoomPrice=").append(bigRoomPrice);
        sb.append(", bigRoomNotes=").append(bigRoomNotes);
        sb.append(", doubleRoomNumber=").append(doubleRoomNumber);
        sb.append(", doubleRoomPrice=").append(doubleRoomPrice);
        sb.append(", doubleRoomNotes=").append(doubleRoomNotes);
        sb.append(", bestRoomNumber=").append(bestRoomNumber);
        sb.append(", bestRoomPrice=").append(bestRoomPrice);
        sb.append(", bestRoomNotes=").append(bestRoomNotes);
        sb.append(", hotelScore=").append(hotelScore);
        sb.append("]");
        return sb.toString();
    }
}