package com.example.weappdemo.bean;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.order_id
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.user_id
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.hotel_id
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.room_type
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private Integer roomType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.enter_date
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private Date enterDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.leave_date
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private Date leaveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.order_state
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private Integer orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.order_id
     *
     * @return the value of order_list.order_id
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Order withOrderId(String orderId) {
        this.setOrderId(orderId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.order_id
     *
     * @param orderId the value for order_list.order_id
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.user_id
     *
     * @return the value of order_list.user_id
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Order withUserId(String userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.user_id
     *
     * @param userId the value for order_list.user_id
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.hotel_id
     *
     * @return the value of order_list.hotel_id
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Order withHotelId(String hotelId) {
        this.setHotelId(hotelId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.hotel_id
     *
     * @param hotelId the value for order_list.hotel_id
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setHotelId(String hotelId) {
        this.hotelId = hotelId == null ? null : hotelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.room_type
     *
     * @return the value of order_list.room_type
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Integer getRoomType() {
        return roomType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Order withRoomType(Integer roomType) {
        this.setRoomType(roomType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.room_type
     *
     * @param roomType the value for order_list.room_type
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setRoomType(Integer roomType) {
        this.roomType = roomType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.enter_date
     *
     * @return the value of order_list.enter_date
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Date getEnterDate() {
        return enterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Order withEnterDate(Date enterDate) {
        this.setEnterDate(enterDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.enter_date
     *
     * @param enterDate the value for order_list.enter_date
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setEnterDate(Date enterDate) {
        this.enterDate = enterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.leave_date
     *
     * @return the value of order_list.leave_date
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Date getLeaveDate() {
        return leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Order withLeaveDate(Date leaveDate) {
        this.setLeaveDate(leaveDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.leave_date
     *
     * @param leaveDate the value for order_list.leave_date
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.order_state
     *
     * @return the value of order_list.order_state
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Order withOrderState(Integer orderState) {
        this.setOrderState(orderState);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.order_state
     *
     * @param orderState the value for order_list.order_state
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", userId=").append(userId);
        sb.append(", hotelId=").append(hotelId);
        sb.append(", roomType=").append(roomType);
        sb.append(", enterDate=").append(enterDate);
        sb.append(", leaveDate=").append(leaveDate);
        sb.append(", orderState=").append(orderState);
        sb.append("]");
        return sb.toString();
    }
}