package com.example.weappdemo.bean;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_list.user_id
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_list.username
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_list.password
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_list.phone_number
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_list.registered_time
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private Date registeredTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_list.user_id
     *
     * @return the value of user_list.user_id
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public User withUserId(String userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_list.user_id
     *
     * @param userId the value for user_list.user_id
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_list.username
     *
     * @return the value of user_list.username
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public User withUsername(String username) {
        this.setUsername(username);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_list.username
     *
     * @param username the value for user_list.username
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_list.password
     *
     * @return the value of user_list.password
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public User withPassword(String password) {
        this.setPassword(password);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_list.password
     *
     * @param password the value for user_list.password
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_list.phone_number
     *
     * @return the value of user_list.phone_number
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public User withPhoneNumber(String phoneNumber) {
        this.setPhoneNumber(phoneNumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_list.phone_number
     *
     * @param phoneNumber the value for user_list.phone_number
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_list.registered_time
     *
     * @return the value of user_list.registered_time
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public Date getRegisteredTime() {
        return registeredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public User withRegisteredTime(Date registeredTime) {
        this.setRegisteredTime(registeredTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_list.registered_time
     *
     * @param registeredTime the value for user_list.registered_time
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    public void setRegisteredTime(Date registeredTime) {
        this.registeredTime = registeredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", registeredTime=").append(registeredTime);
        sb.append("]");
        return sb.toString();
    }
}