server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lqk?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    mapper??
mybatis:
 type-aliases-package: com.example.weappdemo.bean
 mapper-locations: classpath:mapper/*Mapper.xml


#showSql(??sql??)
logging:
  level:
     com.example.weappdemo.mapper: DEBUG
