package com.example.weappdemo.mapper;

import com.example.weappdemo.bean.User;
import com.example.weappdemo.bean.UserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    User selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated Fri Aug 04 10:51:59 CST 2023
     */
    int updateByPrimaryKey(User record);
}